### ISSUE TITLE
Type bool, expected nothing

### ISSUE THREAD

**Issue by felixlinker** [felixlinker/FUPS_modules#6]
https://gyazo.com/3dd22a1a114b91a91c0c72b1e1a7c661

**Comment by Draider97** [comment]
Mission mit FUPS Ordner im Editor geladen, Template Einheit gesetzt, Template Modul gesetzt, Spawn Modul gesetzt, in die Init-Zeile true geschrieben, Fehlermeldung

**Comment by felixlinker** [comment]
In die Init von Spawn Modulen darf kein Rückgabewert sein.
Warum schreibst du da `true` rein?

**Comment by Draider97** [comment]
dachte, dass das initialitionsbedingung bedeutet

**Comment by felixlinker** [comment]
Nein, die init bei Modulen ist in etwa das gleiche wie die init von Einheiten. Da musst du ja auch immer Rückgabewerte mit `null = ...`auffangen, z.B. bei `execVM` oder so.
Also alles so wie es soll, zurück zur Arbeit ;-)
